#!/usr/bin/env bash
# Runs when Claude Code creates a new worktree.
# Generates a .env file in the worktree with an isolated PORT and API_DASHBOARD_DIR.
set -euo pipefail

BRANCH="${CLAUDE_WORKTREE_BRANCH:-}"
WORKTREE_PATH="${CLAUDE_WORKTREE_PATH:-}"

if [[ -z "$BRANCH" || -z "$WORKTREE_PATH" ]]; then
  echo "[worktree-create] Missing CLAUDE_WORKTREE_BRANCH or CLAUDE_WORKTREE_PATH — skipping" >&2
  exit 0
fi

# branch name → safe directory slug (e.g. "feature/my-thing" → "feature-my-thing")
SLUG=$(echo "$BRANCH" | sed 's|/|-|g' | tr -cs 'a-zA-Z0-9-' '-' | sed 's/-\+/-/g' | sed 's/-$//')

# Deterministic port from slug: cksum % 900 + 5100 (range 5100–5999)
# Vite port = server port + 10000 (range 15100–15999, no overlap)
SERVER_PORT=$(( $(printf '%s' "$SLUG" | cksum | cut -d' ' -f1) % 900 + 5100 ))
VITE_PORT=$(( SERVER_PORT + 10000 ))

# Isolated DB directory, sibling of the default ~/.api-dashboard
DB_DIR="$HOME/.api-dashboard-worktrees/$SLUG"

cat > "$WORKTREE_PATH/.env" <<EOF
# Auto-generated by worktree-create hook — do not edit manually.
# Branch: $BRANCH  Slug: $SLUG
PORT=$SERVER_PORT
VITE_PORT=$VITE_PORT
API_DASHBOARD_DIR=$DB_DIR
EOF

echo "[worktree-create] branch=$BRANCH slug=$SLUG server=$SERVER_PORT vite=$VITE_PORT db=$DB_DIR"
