#!/usr/bin/env bash
# WorktreeCreate hook for Claude Code.
# Input: JSON via stdin with fields: worktree_path, base_ref, cwd
# Output: must print worktree_path to stdout (required by Claude Code)
# Non-zero exit aborts worktree creation.
set -euo pipefail

# Read JSON from stdin
INPUT=$(cat)

WORKTREE_PATH=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['worktree_path'])" 2>/dev/null || echo "")
BASE_REF=$(echo "$INPUT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('base_ref',''))" 2>/dev/null || echo "")

if [[ -z "$WORKTREE_PATH" ]]; then
  echo "[worktree-create] Could not parse worktree_path from input" >&2
  exit 1
fi

# Derive slug from worktree path basename (e.g. "feature-context-viz")
SLUG=$(basename "$WORKTREE_PATH" | tr -cs 'a-zA-Z0-9-' '-' | sed 's/-\+/-/g' | sed 's/-$//')

# Deterministic port: cksum % 900 + 5100 (range 5100–5999)
# Vite port = server port + 10000 (range 15100–15999, no overlap)
SERVER_PORT=$(( $(printf '%s' "$SLUG" | cksum | cut -d' ' -f1) % 900 + 5100 ))
VITE_PORT=$(( SERVER_PORT + 10000 ))

# Isolated DB directory
DB_DIR="$HOME/.api-dashboard-worktrees/$SLUG"

cat > "$WORKTREE_PATH/.env" <<EOF
# Auto-generated by worktree-create hook — do not edit manually.
# Base ref: $BASE_REF  Slug: $SLUG
PORT=$SERVER_PORT
VITE_PORT=$VITE_PORT
API_DASHBOARD_DIR=$DB_DIR
EOF

echo "[worktree-create] slug=$SLUG server=$SERVER_PORT vite=$VITE_PORT db=$DB_DIR" >&2

# Required: print worktree path to stdout
echo "$WORKTREE_PATH"
