import { useTranslation } from "react-i18next";

export interface TokenMetric {
  id: string;
  /** Canonical English label — used directly in all UI. Never translated. */
  label: string;
  color: string;
  category: "input" | "cache" | "output" | "context" | "derived";
  unit: "tokens" | "percent";
  /**
   * English description of what this metric measures.
   * Authoritative help-text source — future tooltip/popover components read from here.
   * Not rendered in UI yet this iteration.
   */
  description: string;
  /**
   * How this metric relates to others (formula / accounting identity).
   * Not rendered in UI yet this iteration.
   */
  relation?: string;
  /**
   * i18n key for a localised version of `description`, if provided.
   * UI tooltip components will prefer this when available.
   * Not rendered in UI yet this iteration.
   */
  tooltipKey?: string;
}

export const TOKEN_METRICS: Record<string, TokenMetric> = {
  // Fresh In = input_tokens + cache_creation_input_tokens: all tokens the model processed
  // fresh this call. Cache writes count as fresh (first-time processing), not reuse.
  fresh_input: {
    id: "fresh_input",
    label: "Fresh In",
    color: "#6366f1",
    category: "input",
    unit: "tokens",
    description: "Tokens freshly processed this call: non-cached input + cache writes. Cache writes are first-time processing, not reuse.",
    relation: "Fresh In = input_tokens + cache_write; Total = Fresh In + Cache Read",
    tooltipKey: "metrics.freshInput.tooltip",
  },
  cache_read: {
    id: "cache_read",
    label: "Cache Read",
    color: "#059669",
    category: "cache",
    unit: "tokens",
    description: "Input tokens served from the prompt cache. Higher cache read = lower cost and lower latency.",
    relation: "Part of total input; billed at a discounted rate (~10–25% of input price)",
    tooltipKey: "metrics.cacheRead.tooltip",
  },
  cache_write: {
    id: "cache_write",
    label: "Cache Write",
    color: "#d97706",
    category: "cache",
    unit: "tokens",
    description: "Tokens written to the prompt cache for future reuse. A separate billing item — not input, not output.",
    relation: "Billed independently, typically at a premium (~1.25× input price)",
    tooltipKey: "metrics.cacheWrite.tooltip",
  },
  output: {
    id: "output",
    label: "Output",
    color: "#7c3aed",
    category: "output",
    unit: "tokens",
    description: "Tokens generated by the model in this call. The primary driver of latency tail and output cost.",
    relation: "Total output = Output + Reasoning (if exposed separately)",
    tooltipKey: "metrics.output.tooltip",
  },
  context_used: {
    id: "context_used",
    label: "Context",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Tokens placed in the model's context window for this call. Not the same as billed input tokens.",
    relation: "Context ≈ Fresh In + Cache Read + reused written context",
    tooltipKey: "metrics.contextUsed.tooltip",
  },
  context_delta: {
    id: "context_delta",
    label: "Context Δ",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Change in context size relative to the previous call. Useful for spotting which step inflated the window.",
    tooltipKey: "metrics.contextDelta.tooltip",
  },
  peak_context: {
    id: "peak_context",
    label: "Peak Context",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Largest context window size observed within this session or turn.",
    tooltipKey: "metrics.peakContext.tooltip",
  },
  cache_ratio: {
    id: "cache_ratio",
    label: "Cache Ratio",
    color: "#059669",
    category: "derived",
    unit: "percent",
    description: "Cache read as a share of total reusable input. Formula: cache_read / (fresh_input + cache_read + cache_write).",
    relation: "Higher ratio = better cache efficiency",
    tooltipKey: "metrics.cacheRatio.tooltip",
  },
};

export function getMetric(id: string): TokenMetric {
  const m = TOKEN_METRICS[id];
  if (!m) throw new Error(`Unknown metric id: ${id}`);
  return m;
}

/**
 * Returns the display label (always canonical English) plus the
 * localised tooltip string (when a tooltipKey is defined).
 * Components that only need the label can just read `m.label` directly.
 */
export function useMetricLabel(id: string): { label: string; tooltip: string; color: string } {
  const { t } = useTranslation();
  const m = TOKEN_METRICS[id];
  if (!m) return { label: id, tooltip: "", color: "#6b7280" };
  return {
    label: m.label,
    tooltip: m.tooltipKey ? t(m.tooltipKey, m.description) : m.description,
    color: m.color,
  };
}
