export interface TokenMetric {
  id: string;
  /** Canonical English label — used as fallback when no labelKey translation exists. */
  label: string;
  color: string;
  category: "input" | "cache" | "output" | "context" | "derived";
  unit: "tokens" | "percent";
  description: string;
  relation?: string;
  /** i18n key for localised label, e.g. "metrics.cacheRatio.label". */
  labelKey?: string;
  /** i18n key for localised tooltip/description. */
  tooltipKey?: string;
}

export const TOKEN_METRICS: Record<string, TokenMetric> = {
  // Input ≡ Anthropic API's usage.input_tokens — the non-cached portion of
  // input, billed at the 1× baseline rate. Cache read and cache write are
  // separate buckets. Aligns with the "input" column in `claude /cost`.
  fresh_input: {
    id: "fresh_input",
    label: "Input",
    color: "#6366f1",
    category: "input",
    unit: "tokens",
    description: "Input tokens NOT served from cache and NOT written to cache — the model had to process them fresh this call. Equals the API's usage.input_tokens field, the 1× billing tier.",
    relation: "Input + Cache Read + Cache Write = full prompt size; the three are mutually exclusive Anthropic billing buckets",
    tooltipKey: "metrics.freshInput.tooltip",
  },
  cache_read: {
    id: "cache_read",
    label: "Cache Read",
    color: "#059669",
    category: "cache",
    unit: "tokens",
    description: "Input tokens served from the prompt cache. Higher cache read = lower cost and lower latency.",
    relation: "Part of total input; billed at a discounted rate (~10–25% of input price)",
    tooltipKey: "metrics.cacheRead.tooltip",
  },
  cache_write: {
    id: "cache_write",
    label: "Cache Write",
    color: "#d97706",
    category: "cache",
    unit: "tokens",
    description: "Tokens written to the prompt cache for future reuse. A separate billing item — not input, not output.",
    relation: "Billed independently, typically at a premium (~1.25× input price)",
    tooltipKey: "metrics.cacheWrite.tooltip",
  },
  output: {
    id: "output",
    label: "Output",
    color: "#7c3aed",
    category: "output",
    unit: "tokens",
    description: "Tokens generated by the model in this call. The primary driver of latency tail and output cost.",
    relation: "Total output = Output + Reasoning (if exposed separately)",
    tooltipKey: "metrics.output.tooltip",
  },
  context_used: {
    id: "context_used",
    label: "Context",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Tokens placed in the model's context window for this call. Not the same as billed input tokens.",
    relation: "Context = Input + Cache Read + Cache Write (the three Anthropic input buckets)",
    tooltipKey: "metrics.contextUsed.tooltip",
  },
  context_delta: {
    id: "context_delta",
    label: "Context Δ",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Change in context size relative to the previous call. Useful for spotting which step inflated the window.",
    tooltipKey: "metrics.contextDelta.tooltip",
  },
  peak_context: {
    id: "peak_context",
    label: "Peak Context",
    color: "#6366f1",
    category: "context",
    unit: "tokens",
    description: "Largest context window size observed within this session or turn.",
    tooltipKey: "metrics.peakContext.tooltip",
  },
  cache_ratio: {
    id: "cache_ratio",
    label: "Cache Ratio",
    color: "#059669",
    category: "derived",
    unit: "percent",
    description: "Cache read as a share of total prompt input. Formula: cache_read / (input + cache_read + cache_write).",
    relation: "Higher ratio = better cache efficiency",
    labelKey: "metrics.cacheRatio.label",
    tooltipKey: "metrics.cacheRatio.tooltip",
  },
};
