#!/usr/bin/env bash
# Detects whether we're running inside a git worktree.
# If so, derives PORT / VITE_PORT / API_DASHBOARD_DIR from the branch name
# and writes .env into the current directory (if not already present).
# In the main repo, this script is a no-op.
set -euo pipefail

# ── Detect worktree ───────────────────────────────────────────────────────────

GIT_COMMON=$(git rev-parse --git-common-dir 2>/dev/null || echo "")
GIT_DIR=$(git rev-parse --git-dir 2>/dev/null || echo "")

# In a worktree, --git-common-dir points to the main repo's .git (absolute path)
# In the main repo, both return ".git"
if [[ -z "$GIT_COMMON" || "$GIT_COMMON" == ".git" || "$GIT_COMMON" == "$GIT_DIR" ]]; then
  echo "[setup-env] Main repo detected — skipping .env generation"
  exit 0
fi

# ── Already configured ────────────────────────────────────────────────────────

if [[ -f ".env" ]]; then
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  RECORDED_BRANCH=$(grep '^# Branch:' .env 2>/dev/null | sed 's/^# Branch: //' || echo "")
  if [[ "$CURRENT_BRANCH" == "$RECORDED_BRANCH" ]]; then
    echo "[setup-env] .env already configured for branch '$CURRENT_BRANCH' — skipping"
    exit 0
  fi
  echo "[setup-env] Branch changed ($RECORDED_BRANCH → $CURRENT_BRANCH), regenerating .env"
fi

# ── Derive config from branch name ───────────────────────────────────────────

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
SLUG=$(echo "$BRANCH" | sed 's|/|-|g' | tr -cs 'a-zA-Z0-9-' '-' | sed 's/-\+/-/g' | sed 's/-$//')

# Deterministic port: cksum % 900 + 5100 (range 5100–5999)
# Vite port: server port + 10000 (range 15100–15999, no overlap)
SERVER_PORT=$(( $(printf '%s' "$SLUG" | cksum | cut -d' ' -f1) % 900 + 5100 ))
VITE_PORT=$(( SERVER_PORT + 10000 ))
DB_DIR="$HOME/.api-dashboard-worktrees/$SLUG"

# ── Write .env ────────────────────────────────────────────────────────────────

cat > .env <<EOF
# Auto-generated by scripts/setup-env.sh — do not edit manually.
# Branch: $BRANCH
# Slug: $SLUG
PORT=$SERVER_PORT
VITE_PORT=$VITE_PORT
API_DASHBOARD_DIR=$DB_DIR
EOF

echo "[setup-env] Worktree '$BRANCH' → PORT=$SERVER_PORT VITE_PORT=$VITE_PORT DB=$DB_DIR"
