// render-reconcile-fusion-html.ts — Fused 4-column Reconcile View
//
// Mirrors the layout style of proxy-attribution-view.ts but unifies all four
// perspectives in a single scrollable table:
//
//   col-1  Raw          — reqBody original text (proxy fact, same as attr-view col-1)
//   col-2  Attribution  — parser segment metadata + rule attribution
//   col-3  Expected     — expected segment text, rendered like col-1 (virtual request)
//   col-4  Reconcile    — alignment kind, basis, comparisonGrade, char delta
//
// Header: coverage bucket stacked bar (v2 scorecard breakdown) with tooltips.
// All metric labels are English; descriptions appear in tooltip (title=).
//
// Bypath: no context-ledger core code touched.

import type { ReconciliationReport, ContextSegment, ProxySegmentAttribution, AlignmentRef } from "../types";
import type { QueryScorecard } from "./types";

// ── Coverage buckets ──────────────────────────────────────────────────────────

interface Bucket { key: keyof QueryScorecard; label: string; color: string; tip: string; }

const BUCKETS: Bucket[] = [
  { key: "wireExactCoverage",        label: "Wire Exact",       color: "#22c55e",
    tip: "basis=raw_hash or tool_use_id — raw byte-level exact match; highest confidence anchor" },
  { key: "canonicalExactCoverage",   label: "Canonical Exact",  color: "#86efac",
    tip: "basis=normalized_hash — identical after whitespace/encoding normalization" },
  { key: "templateCoverage",         label: "Template",         color: "#a3e635",
    tip: "basis=rule_id + materialization=exact_text — rule content pattern matched literally" },
  { key: "regexCoverage",            label: "Regex",            color: "#fbbf24",
    tip: "basis=rule_id + materialization=shape/normalized_text — regex pattern match only; no verbatim text" },
  { key: "presenceCoverage",         label: "Presence",         color: "#fb923c",
    tip: "basis=harness_rule/category — category+role heuristic only; no content anchor" },
  { key: "serverSideCoverage",       label: "Server-side",      color: "#94a3b8",
    tip: "basis=server_side_attribution — known server overhead (billing_noise etc.); not user-semantic" },
  { key: "attributionOnlyCoverage",  label: "Attribution Only", color: "#c084fc",
    tip: "basis=attribution_only — attribution recognized but no matching expected segment (U1-U5 gap)" },
  { key: "unexplainedCoverage",      label: "Unexplained",      color: "#ef4444",
    tip: "No attribution and no alignment — root-cause investigation needed" },
];

// ── Alignment kind styling ────────────────────────────────────────────────────

const KIND_STYLE: Record<string, { color: string; bg: string; label: string; tip: string }> = {
  matched:                 { color: "#166534", bg: "#dcfce7", label: "matched",
    tip: "Content-anchored exact or near-exact match (raw_hash / tool_use_id / rule_id)" },
  approximate_match:       { color: "#92400e", bg: "#fef9c3", label: "≈ match",
    tip: "Content anchor found but char count differs by > 1% — text may have drifted" },
  suspect_match:           { color: "#9a3412", bg: "#fff7ed", label: "suspect",
    tip: "Aligned only by category+role heuristic; no content anchor — treat as unverified" },
  expected_only:           { color: "#1e40af", bg: "#dbeafe", label: "expected only",
    tip: "Expected segment has no proxy counterpart — possible missing injection" },
  proxy_only:              { color: "#991b1b", bg: "#fee2e2", label: "proxy only",
    tip: "Proxy segment not covered by any alignment — truly unexplained content" },
  attribution_only:        { color: "#6b21a8", bg: "#f3e8ff", label: "attr only",
    tip: "Server-side attribution recognized (e.g. billing_noise) but no expected segment" },
  server_side_attribution: { color: "#374151", bg: "#f3f4f6", label: "server-side",
    tip: "Known server-side overhead — not generated by user mutations" },
};

// ── Comparison grade ──────────────────────────────────────────────────────────

const GRADE_TIP: Record<string, string> = {
  exact:      "Raw wire bytes or tool_use_id exactly match",
  normalized: "Normalized hash match (whitespace/encoding differences only)",
  template:   "Rule content pattern matched literally (exact_text materialization)",
  regex:      "Rule regex pattern match; content can only be approximated",
  presence:   "Category/role heuristic only — no content evidence",
  none:       "No alignment",
};

// ── HTML helpers ──────────────────────────────────────────────────────────────

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function fmtK(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}

function pctFmt(n: number): string { return `${(n * 100).toFixed(1)}%`; }

function badge(text: string, color: string, bg: string, tip?: string): string {
  const t = tip ? ` title="${esc(tip)}"` : "";
  return `<span class="badge"${t} style="color:${color};background:${bg}">${esc(text)}</span>`;
}

function confBadge(conf: string): string {
  const MAP: Record<string, [string, string, string]> = {
    exact:     ["#166534", "#dcfce7", "Confidence: exact — content fully reproducible"],
    estimated: ["#92400e", "#fef9c3", "Confidence: estimated — content approximated via rule template"],
    inferred:  ["#374151", "#f3f4f6", "Confidence: inferred — presence/heuristic match only"],
    unknown:   ["#991b1b", "#fee2e2", "Confidence: unknown"],
  };
  const [c, bg, tip] = MAP[conf] ?? ["#6b7280", "#f3f4f6", conf];
  return badge(conf, c, bg, tip);
}

// ── Raw text extraction (mirrors proxy-attribution-view col-1) ────────────────

function walkPath(path: string, root: unknown): unknown {
  const tokens = path.split(/\.|\[(\d+)\]/).filter((t) => t !== undefined && t !== "");
  let cur: unknown = root;
  for (const tok of tokens) {
    if (cur === null || cur === undefined) return undefined;
    const idx = parseInt(tok, 10);
    if (!isNaN(idx)) cur = (cur as unknown[])[idx];
    else cur = (cur as Record<string, unknown>)[tok];
  }
  return cur;
}

function extractRaw(seg: ContextSegment, reqBody: Record<string, unknown>): string | null {
  const ref = seg.sourceRefs[0];
  if (!ref || ref.kind !== "proxy" || !ref.proxy.jsonPath) return seg.rawText ?? null;
  const path = ref.proxy.jsonPath.startsWith("reqBody.") ? ref.proxy.jsonPath.slice(8) : ref.proxy.jsonPath;
  const value = walkPath(path, reqBody);
  if (value === undefined || value === null) return seg.rawText ?? null;
  if (typeof value === "object" && !Array.isArray(value)) {
    const obj = value as Record<string, unknown>;
    if (typeof obj["text"] === "string") {
      const text = obj["text"] as string;
      const range = ref.proxy.charRange;
      return range ? text.slice(range.start, range.end) : text;
    }
    return JSON.stringify(obj, null, 2);
  }
  if (typeof value === "string") return value;
  return JSON.stringify(value, null, 2);
}

function extractExpectedText(seg: ContextSegment): string | null {
  if (seg.contentRef?.kind === "inline" && seg.contentRef.text) return seg.contentRef.text;
  if (seg.rawText) return seg.rawText;
  if (seg.contentRef?.preview) return `[preview] ${seg.contentRef.preview}`;
  return null;
}

// ── Coverage header ───────────────────────────────────────────────────────────

function renderCoverageHeader(sc: QueryScorecard): string {
  // Stacked bar
  let offset = 0;
  const segs = BUCKETS.map((b) => {
    const val = (sc[b.key] as number) ?? 0;
    if (val < 0.001) return "";
    const w = val * 100;
    const seg = `<div style="position:absolute;left:${offset.toFixed(3)}%;width:${w.toFixed(3)}%;height:100%;background:${b.color};" title="${esc(b.label + ': ' + pctFmt(val) + ' — ' + b.tip)}"></div>`;
    offset += w;
    return seg;
  }).join("");

  const legendItems = BUCKETS.map((b) => {
    const val = (sc[b.key] as number) ?? 0;
    if (val < 0.001) return "";
    return `
      <div class="legend-item" title="${esc(b.tip)}">
        <span class="legend-dot" style="background:${b.color}"></span>
        <span class="legend-name">${esc(b.label)}</span>
        <span class="legend-pct">${pctFmt(val)}</span>
      </div>`;
  }).join("");

  const riskFlags = [
    sc.regexOverreachRisk > 0.4 ? `<span class="risk-flag" title="regex pattern covers &gt;40% of proxy chars — patterns may be too broad">regex overreach ${pctFmt(sc.regexOverreachRisk)}</span>` : "",
    (sc.pendingRuleCoverage ?? 0) > 0.2 ? `<span class="risk-flag" style="background:#fdf4ff;border-color:#d8b4fe;color:#6b21a8" title="rules with verifiedFor=null cover &gt;20% of proxy chars — verification gap">pending rules ${pctFmt(sc.pendingRuleCoverage!)}</span>` : "",
  ].filter(Boolean).join(" ");

  const verdictTip: Record<string, string> = {
    ok: "No significant changes; metrics within thresholds",
    improvement: "wireExact + template coverage improved or unexplained decreased",
    regression: "falseReliableMatchCount > 0, or wireExact + template coverage dropped significantly",
    needs_review: "New query / drift detected / prefixIncomplete / pendingRuleCoverage > 30%",
    unchanged: "Identical to baseline",
    skipped: "proxy_without_jsonl or required inputs missing",
    failed: "Pipeline threw an exception",
  };

  return `
<div class="cov-header">
  <div class="cov-title-row">
    <span class="cov-title">Coverage</span>
    <span class="verdict-chip verdict-${esc(sc.verdict ?? 'ok')}" title="${esc(verdictTip[sc.verdict ?? 'ok'] ?? '')}">${esc(sc.verdict ?? 'ok')}</span>
    <span class="cov-chars" title="Total proxy chars (denominator for all coverage ratios)">${fmtK(sc.proxyChars)} proxy chars</span>
    ${riskFlags}
  </div>

  <!-- Stacked bar -->
  <div class="stacked-bar-wrap" title="Proportional breakdown of proxy chars into coverage buckets">
    <div style="position:relative;height:100%">${segs}</div>
  </div>

  <!-- Legend -->
  <div class="cov-legend">${legendItems}</div>

  <!-- Key metrics row -->
  <div class="metrics-strip">
    <div class="metric" title="wireExactCoverage + canonicalExactCoverage — strongest evidence tier">
      <div class="metric-label">Wire+Canonical</div>
      <div class="metric-val">${pctFmt((sc.wireExactCoverage ?? 0) + (sc.canonicalExactCoverage ?? 0))}</div>
    </div>
    <div class="metric" title="${esc(BUCKETS[2].tip)}">
      <div class="metric-label">Template</div>
      <div class="metric-val">${pctFmt(sc.templateCoverage ?? 0)}</div>
    </div>
    <div class="metric" title="${esc(BUCKETS[3].tip)}">
      <div class="metric-label">Regex</div>
      <div class="metric-val">${pctFmt(sc.regexCoverage ?? 0)}</div>
    </div>
    <div class="metric" title="Segments that have attribution but no matching expected segment (U1-U5 reconstruction gap)">
      <div class="metric-label">Attr Only</div>
      <div class="metric-val">${pctFmt(sc.attributionOnlyCoverage ?? 0)}</div>
    </div>
    <div class="metric metric-danger" title="${esc(BUCKETS[7].tip)}">
      <div class="metric-label">Unexplained</div>
      <div class="metric-val">${pctFmt(sc.unexplainedCoverage ?? 0)}</div>
    </div>
    <div class="metric" title="Char drift across evidence-backed aligned segments — 0% means aligned segments have identical char counts, not that proxy == expected">
      <div class="metric-label">Aligned Drift</div>
      <div class="metric-val">${pctFmt(sc.alignedTextDrift ?? 0)}</div>
    </div>
    ${sc.requestLevelExact ? `
    <div class="metric" title="Request-level exact match level: raw (wire bytes) > canonical > structural > segment-only">
      <div class="metric-label">Req Exact</div>
      <div class="metric-val">${esc(sc.requestLevelExact)}</div>
    </div>` : ""}
  </div>
</div>`;
}

// ── Col-1: Raw original text ──────────────────────────────────────────────────

function renderRawCol(seg: ContextSegment, reqBody: Record<string, unknown>): string {
  const raw = extractRaw(seg, reqBody);
  const ref = seg.sourceRefs[0];
  const jsonPath = ref?.kind === "proxy" ? (ref.proxy.jsonPath ?? "?") : "?";
  const range = ref?.kind === "proxy" ? ref.proxy.charRange : undefined;
  const rangeStr = range ? `[${range.start}…${range.end})` : "";
  const chars = raw?.length ?? seg.charCount ?? 0;

  return `
<div class="raw-col">
  <div class="path-line">
    <code class="json-path" title="JSON path in reqBody">${esc(jsonPath)}</code>
    ${rangeStr ? `<span class="range-hint" title="char slice within block">${esc(rangeStr)}</span>` : ""}
    <span class="char-count" title="character count">${fmtK(chars)}c</span>
  </div>
  ${raw
    ? `<pre class="raw-text">${esc(raw.slice(0, 3000))}${raw.length > 3000 ? "\n…(truncated)" : ""}</pre>`
    : `<span class="no-content">—</span>`
  }
</div>`;
}

// ── Col-2: Attribution (parser + rule) ───────────────────────────────────────

function renderAttrCol(seg: ContextSegment, attr: ProxySegmentAttribution | undefined): string {
  const catColor: Record<string, string> = {
    billing_noise: "#6b7280", system_prompt: "#3b82f6", harness_injection: "#8b5cf6",
    tools_schema: "#f59e0b", tool_use: "#10b981", tool_result: "#059669",
    user_message: "#0ea5e9", assistant_text: "#64748b", local_command_history: "#d97706",
    prior_session_history: "#a78bfa", unknown: "#ef4444",
  };
  const cc = catColor[seg.category] ?? "#94a3b8";
  const meta = seg.metadata as Record<string, unknown> | undefined;
  const sectionHeader = typeof meta?.["sectionHeader"] === "string" ? meta["sectionHeader"] : null;

  const attrPart = attr ? `
    <div class="attr-line">
      ${badge(attr.category, catColor[attr.category] ?? "#94a3b8", `${catColor[attr.category] ?? "#94a3b8"}18`,
        `Attribution category — mechanism: ${attr.mechanism}`)}
      <code class="mechanism" title="Attribution mechanism: how this segment was identified">${esc(attr.mechanism)}</code>
    </div>
    <div class="conf-line">
      <span title="Classification confidence: certainty that this segment belongs to the attributed category">${confBadge(attr.classificationConfidence)} cls</span>
      <span title="Materialization confidence: ability to reproduce the exact text of this segment">${confBadge(attr.materializationConfidence)} mat</span>
    </div>
    ${attr.ruleId ? `<div class="rule-id" title="Rule ID that matched this segment"><code>${esc(attr.ruleId)}</code></div>` : ""}
    ${attr.notes?.length ? `<details class="attr-notes"><summary title="Attribution notes from the rule engine">${attr.notes.length} note${attr.notes.length > 1 ? "s" : ""}</summary><ul>${attr.notes.map((n) => `<li>${esc(n)}</li>`).join("")}</ul></details>` : ""}
  ` : `<div class="no-attr" title="No attribution available for this segment">— no attribution —</div>`;

  return `
<div class="attr-col">
  <div class="seg-id" title="Segment ID"><code>${esc(seg.id.slice(-12))}</code></div>
  <div class="seg-badges">
    ${badge(seg.section, "#475569", "#f1f5f9", "Section: which part of the request this segment belongs to")}
    ${badge(seg.category, cc, `${cc}18`, "Parser category — may be overridden by attribution")}
    ${seg.lifecycle ? badge(seg.lifecycle, "#475569", "#f1f5f9", `Lifecycle: expected duration of this content in the context`) : ""}
    ${seg.flags?.includes("large_segment") ? badge("large", "#991b1b", "#fee2e2", "This segment is unusually large") : ""}
    ${seg.flags?.includes("known_noise") ? badge("noise", "#6b7280", "#f3f4f6", "Known non-semantic noise (e.g. billing counter)") : ""}
    ${seg.cacheHint && seg.cacheHint !== "none" ? badge(seg.cacheHint, "#92400e", "#fef9c3", `Cache hint: ${seg.cacheHint}`) : ""}
  </div>
  ${sectionHeader ? `<div class="section-hdr" title="Section header extracted from system prompt">§ ${esc(sectionHeader)}</div>` : ""}
  ${seg.charCount !== undefined ? `<div class="seg-chars" title="Char count measured from proxy source">${fmtK(seg.charCount)}c</div>` : ""}
  ${attrPart}
</div>`;
}

// ── Col-3: Expected segment text ──────────────────────────────────────────────

function renderExpectedCol(segs: ContextSegment[]): string {
  if (segs.length === 0) {
    return `<div class="expected-col expected-empty" title="No expected segment aligned to this proxy segment">—</div>`;
  }

  const parts = segs.map((eseg) => {
    const text = extractExpectedText(eseg);
    const chars = eseg.charCount ?? text?.length ?? 0;
    const catColor: Record<string, string> = {
      billing_noise: "#6b7280", system_prompt: "#3b82f6", harness_injection: "#8b5cf6",
      tools_schema: "#f59e0b", tool_use: "#10b981", tool_result: "#059669",
      user_message: "#0ea5e9", assistant_text: "#64748b",
    };
    const cc = catColor[eseg.category] ?? "#94a3b8";
    const ref = eseg.sourceRefs[0];
    const sourceKind = ref?.kind ?? "unknown";

    return `
<div class="expected-seg">
  <div class="path-line">
    <code class="json-path" title="Expected segment ID">${esc(eseg.id.slice(-12))}</code>
    <span class="char-count" title="Expected char count">${fmtK(chars)}c</span>
    ${badge(eseg.category, cc, `${cc}18`, "Expected segment category")}
    <span class="source-kind" title="Source of this expected segment (jsonl = from JSONL mutations; harness_rule = from rule registry)">${esc(sourceKind)}</span>
  </div>
  ${text
    ? `<pre class="raw-text">${esc(text.slice(0, 3000))}${text.length > 3000 ? "\n…(truncated)" : ""}</pre>`
    : `<span class="no-content" title="No inline text available — char count only">${fmtK(chars)}c (no text)</span>`
  }
</div>`;
  });

  return `<div class="expected-col">${parts.join("")}</div>`;
}

// ── Col-4: Reconcile result ───────────────────────────────────────────────────

function renderReconcileCol(
  alignState: AlignState | undefined,
  proxySeg: ContextSegment,
  expectedSegs: ContextSegment[],
): string {
  if (!alignState) {
    return `<div class="recon-col recon-missing" title="No reconciliation alignment for this proxy segment">— no alignment —</div>`;
  }

  const style = KIND_STYLE[alignState.kind] ?? KIND_STYLE["server_side_attribution"];
  const align = alignState.alignment;

  const proxyChars = proxySeg.charCount ?? 0;
  const expectedChars = expectedSegs.reduce((s, e) => s + (e.charCount ?? 0), 0);
  const delta = expectedSegs.length > 0 && proxyChars > 0 ? expectedChars - proxyChars : undefined;
  const deltaPct = delta !== undefined && proxyChars > 0 ? Math.abs(delta) / proxyChars : undefined;

  const gradeTip = align?.comparisonGrade ? (GRADE_TIP[align.comparisonGrade] ?? align.comparisonGrade) : "";

  return `
<div class="recon-col">
  <div class="recon-kind" title="${esc(style.tip)}">
    <span style="display:inline-block;padding:2px 7px;border-radius:4px;font-size:10px;font-weight:700;color:${style.color};background:${style.bg}">${esc(style.label)}</span>
  </div>
  ${align ? `
  <div class="recon-meta">
    ${badge(align.basis, "#334155", "#f1f5f9", `Alignment basis — how the match was established: ${align.basis}`)}
    ${badge(align.comparisonGrade, "#334155", "#f1f5f9", gradeTip)}
    ${badge(align.confidence, "#334155", "#f1f5f9", `Overall alignment confidence`)}
  </div>
  ` : ""}
  ${delta !== undefined ? `
  <div class="char-delta ${delta > 0 ? "delta-pos" : delta < 0 ? "delta-neg" : "delta-zero"}"
       title="expectedChars − proxyChars; positive = expected is larger, negative = proxy is larger">
    Δ${delta > 0 ? "+" : ""}${delta.toLocaleString()}c${deltaPct !== undefined ? ` (${pctFmt(deltaPct)})` : ""}
  </div>` : ""}
  ${align?.note ? `<div class="recon-note" title="Alignment note from reconciliation engine">${esc(align.note.slice(0, 120))}</div>` : ""}
</div>`;
}

// ── Row building ──────────────────────────────────────────────────────────────

interface AlignState {
  kind: string;
  alignment: AlignmentRef | undefined;
  expectedSegs: ContextSegment[];
}

function buildAlignIndex(report: ReconciliationReport): Map<string, AlignState> {
  const idx = new Map<string, AlignState>();
  const expectedById = new Map((report.expected?.segments ?? []).map((s) => [s.id, s]));
  const attrByProxyId = new Map<string, string>();
  for (const a of report.proxyAttributions) {
    for (const id of a.proxySegmentIds) attrByProxyId.set(id, a.category);
  }

  for (const align of report.alignments) {
    let kind = "matched";
    if (align.expectedSegmentIds.length === 0) {
      kind = align.note?.startsWith("billing_noise") ? "server_side_attribution" : "attribution_only";
    } else {
      // check if every proxy segment is billing_noise by attribution
      const pSegs = align.proxySegmentIds;
      if (pSegs.length > 0 && pSegs.every((id) => attrByProxyId.get(id) === "billing_noise")) {
        kind = "server_side_attribution";
      } else if (align.basis === "category") {
        kind = "suspect_match";
      } else if (align.comparisonGrade === "exact" || align.comparisonGrade === "normalized"
                 || align.comparisonGrade === "template") {
        kind = "matched";
      } else {
        kind = "approximate_match";
      }
    }

    const expectedSegs = align.expectedSegmentIds
      .map((id) => expectedById.get(id)).filter(Boolean) as ContextSegment[];
    const state: AlignState = { kind, alignment: align, expectedSegs };
    for (const id of align.proxySegmentIds) idx.set(id, state);
  }
  return idx;
}

function buildExpectedOnlyList(report: ReconciliationReport): ContextSegment[] {
  const covered = new Set<string>();
  for (const a of report.alignments) for (const id of a.expectedSegmentIds) covered.add(id);
  return (report.expected?.segments ?? []).filter((s) => !covered.has(s.id));
}

function buildAttrIndex(report: ReconciliationReport): Map<string, ProxySegmentAttribution> {
  const m = new Map<string, ProxySegmentAttribution>();
  for (const a of report.proxyAttributions) for (const id of a.proxySegmentIds) m.set(id, a);
  return m;
}

// ── Section grouping ──────────────────────────────────────────────────────────

const SECTION_ORDER = ["system", "tools", "messages", "metadata", "unknown"];

// ── Main export ───────────────────────────────────────────────────────────────

export interface ReconcileFusionInput {
  queryId: string;
  sessionId: string;
  timestamp: string;
  report: ReconciliationReport;
  reqBody: Record<string, unknown>;
  scorecard: QueryScorecard;
}

export function renderReconcileFusionHtml(input: ReconcileFusionInput): string {
  const { queryId, sessionId, timestamp, report, reqBody, scorecard } = input;

  const alignIdx = buildAlignIndex(report);
  const attrIdx = buildAttrIndex(report);
  const expectedOnlySegs = buildExpectedOnlyList(report);
  const expectedById = new Map((report.expected?.segments ?? []).map((s) => [s.id, s]));

  const covHeader = renderCoverageHeader(scorecard);

  // Group proxy segments by section
  const grouped = new Map<string, ContextSegment[]>();
  for (const s of SECTION_ORDER) grouped.set(s, []);
  for (const seg of report.snapshot.segments) {
    const key = seg.section;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(seg);
  }

  const sectionBlocks = [...grouped.entries()]
    .filter(([, segs]) => segs.length > 0)
    .map(([section, segs]) => {
      const totalChars = segs.reduce((s, seg) => s + (seg.charCount ?? 0), 0);
      const rows = segs.map((seg) => {
        const alignState = alignIdx.get(seg.id);
        const attr = attrIdx.get(seg.id);
        const expSegs = alignState?.expectedSegs ?? [];
        return `
<tr class="seg-row" data-segid="${esc(seg.id)}">
  <td class="col-raw">${renderRawCol(seg, reqBody)}</td>
  <td class="col-attr">${renderAttrCol(seg, attr)}</td>
  <td class="col-expected">${renderExpectedCol(expSegs)}</td>
  <td class="col-recon">${renderReconcileCol(alignState, seg, expSegs)}</td>
</tr>`;
      }).join("");

      return `
<tr class="section-row">
  <td colspan="4">
    <div class="section-banner">
      <span class="section-name" title="Request section">${esc(section)}</span>
      <span class="section-stats">${segs.length} segments · ${fmtK(totalChars)}c</span>
    </div>
  </td>
</tr>
${rows}`;
    }).join("");

  // expected-only rows
  const expectedOnlyBlock = expectedOnlySegs.length > 0 ? `
<tr class="section-row">
  <td colspan="4">
    <div class="section-banner" style="border-color:#3b82f6">
      <span class="section-name" style="color:#3b82f6" title="Expected segments that have no proxy counterpart">expected only</span>
      <span class="section-stats">${expectedOnlySegs.length} segments · no proxy counterpart</span>
    </div>
  </td>
</tr>
${expectedOnlySegs.map((eseg) => `
<tr class="seg-row expected-only-row">
  <td class="col-raw"><span class="no-content" title="No proxy raw text — this segment only exists in expected">—</span></td>
  <td class="col-attr">
    <div class="attr-col">
      <div class="seg-id" title="Expected segment ID (no proxy counterpart)"><code>${esc(eseg.id.slice(-12))}</code></div>
      <div class="seg-badges">${(() => { const c = "#3b82f6"; return badge(eseg.section, "#1e40af", "#dbeafe", "Section") + " " + badge(eseg.category, c, `${c}18`, "Category"); })()}</div>
    </div>
  </td>
  <td class="col-expected">${renderExpectedCol([eseg])}</td>
  <td class="col-recon">
    <div class="recon-col">
      <span style="display:inline-block;padding:2px 7px;border-radius:4px;font-size:10px;font-weight:700;color:#1e40af;background:#dbeafe"
            title="Expected segment has no proxy counterpart — possible missing injection or reconstruction gap">expected only</span>
    </div>
  </td>
</tr>`).join("")}` : "";

  // summary stats
  const matched    = report.alignments.filter((a) => a.expectedSegmentIds.length > 0).length;
  const attrOnly   = report.alignments.filter((a) => a.expectedSegmentIds.length === 0 && !a.note?.startsWith("billing_noise")).length;
  const serverSide = report.alignments.filter((a) => a.note?.startsWith("billing_noise")).length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Reconcile Fusion · ${esc(queryId.slice(-16))}</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: ui-monospace, "Cascadia Code", "Fira Code", monospace;
       font-size: 12px; background: #0f172a; color: #e2e8f0; }

/* ── coverage header ── */
.cov-header { padding: 14px 18px; border-bottom: 1px solid #1e293b; background: #1e293b; }
.cov-title-row { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 8px; }
.cov-title { font-size: 13px; font-weight: 700; color: #f1f5f9; }
.cov-chars { font-size: 11px; color: #64748b; }
.risk-flag { font-size: 10px; padding: 1px 6px; border-radius: 3px; border: 1px solid #fde047;
             background: #fef9c3; color: #713f12; }

/* verdict chip */
.verdict-chip { display: inline-block; padding: 1px 7px; border-radius: 4px;
                font-size: 11px; font-weight: 700; cursor: default; }
.verdict-ok            { background: #052e16; color: #4ade80; }
.verdict-improvement   { background: #022c22; color: #34d399; }
.verdict-regression    { background: #450a0a; color: #f87171; }
.verdict-needs_review  { background: #451a03; color: #fbbf24; }
.verdict-unchanged     { background: #1e293b; color: #94a3b8; }
.verdict-skipped       { background: #1e293b; color: #64748b; }
.verdict-failed        { background: #450a0a; color: #fca5a5; }

/* stacked bar */
.stacked-bar-wrap { height: 14px; background: #334155; border-radius: 4px;
                    overflow: hidden; margin-bottom: 8px; cursor: default; }

/* legend */
.cov-legend { display: flex; gap: 10px 20px; flex-wrap: wrap; margin-bottom: 10px; }
.legend-item { display: flex; align-items: center; gap: 5px; cursor: default; }
.legend-dot  { width: 8px; height: 8px; border-radius: 2px; flex-shrink: 0; }
.legend-name { font-size: 10px; color: #94a3b8; }
.legend-pct  { font-size: 10px; font-weight: 700; color: #e2e8f0; }

/* metrics strip */
.metrics-strip { display: flex; gap: 0; padding-top: 8px; border-top: 1px solid #334155;
                 flex-wrap: wrap; }
.metric { padding: 0 14px 0 0; min-width: 90px; }
.metric:not(:first-child) { padding-left: 14px; border-left: 1px solid #334155; }
.metric-label { font-size: 9px; color: #64748b; text-transform: uppercase;
                letter-spacing: 0.07em; margin-bottom: 2px; }
.metric-val { font-size: 16px; font-weight: 700; color: #e2e8f0; }
.metric-danger .metric-val { color: #f87171; }

/* ── page header ── */
.view-header { padding: 10px 18px; border-bottom: 1px solid #1e293b; background: #0f172a; }
.view-title { font-size: 13px; font-weight: 700; color: #f1f5f9; }
.view-meta { font-size: 10px; color: #64748b; margin-top: 3px; }
.view-meta b { color: #94a3b8; }
.summary-row { margin-top: 6px; display: flex; gap: 14px; flex-wrap: wrap; align-items: center; }
.stat { font-size: 11px; color: #94a3b8; }
.stat b { color: #e2e8f0; }

/* ── table ── */
table { width: 100%; border-collapse: collapse; table-layout: fixed; }
col.col-raw      { width: 28%; }
col.col-attr     { width: 20%; }
col.col-expected { width: 28%; }
col.col-recon    { width: 24%; }

/* ── section banner ── */
.section-row td { padding: 0; }
.section-banner { padding: 5px 12px; background: #1e293b;
                  border-top: 2px solid #334155; display: flex; gap: 10px; align-items: center; }
.section-name  { font-weight: 700; color: #7dd3fc; font-size: 11px;
                 text-transform: uppercase; letter-spacing: 0.08em; }
.section-stats { color: #475569; font-size: 11px; }

/* ── segment rows ── */
.seg-row td { padding: 8px 10px; vertical-align: top; border-bottom: 1px solid #1e293b; }
.seg-row:hover td { background: #1e293b60; }
.expected-only-row td { background: #0c1a30; }
.expected-only-row:hover td { background: #0e2040; }

/* ── col-1: raw ── */
.raw-col .path-line { display: flex; align-items: center; gap: 5px; flex-wrap: wrap; margin-bottom: 4px; }
.json-path { color: #7dd3fc; font-size: 10px; }
.range-hint { color: #475569; font-size: 10px; }
.char-count { color: #475569; font-size: 10px; }
.raw-text { font-size: 10px; white-space: pre-wrap; word-break: break-all; color: #cbd5e1;
            max-height: 200px; overflow-y: auto; border: 1px solid #1e293b;
            border-radius: 3px; padding: 5px; background: #080f1a; line-height: 1.5; }
.no-content { color: #334155; font-size: 11px; }

/* ── col-2: attribution ── */
.attr-col .seg-id code { color: #a78bfa; font-size: 9px; display: block; margin-bottom: 3px; }
.seg-badges { display: flex; gap: 3px; flex-wrap: wrap; margin-bottom: 3px; }
.section-hdr { color: #fbbf24; font-size: 10px; margin-top: 2px; }
.seg-chars { color: #475569; font-size: 10px; margin-top: 2px; }
.attr-line { display: flex; align-items: center; gap: 4px; flex-wrap: wrap; margin-top: 4px; }
.mechanism { color: #64748b; font-size: 9px; }
.conf-line { display: flex; gap: 6px; align-items: center; flex-wrap: wrap; margin-top: 3px;
             font-size: 10px; color: #94a3b8; }
.rule-id code { color: #34d399; font-size: 9px; display: block; margin-top: 2px; }
.attr-notes summary { cursor: pointer; font-size: 10px; color: #64748b; margin-top: 3px; }
.attr-notes ul { padding-left: 10px; margin-top: 3px; }
.attr-notes li { font-size: 10px; color: #94a3b8; margin-bottom: 2px; }
.no-attr { color: #334155; font-size: 11px; margin-top: 4px; }

/* ── col-3: expected ── */
.expected-col { }
.expected-empty { color: #334155; padding: 4px 0; }
.expected-seg { margin-bottom: 6px; }
.expected-seg:last-child { margin-bottom: 0; }
.source-kind { font-size: 9px; color: #475569; }

/* ── col-4: reconcile ── */
.recon-col { }
.recon-missing { color: #334155; }
.recon-kind { margin-bottom: 4px; }
.recon-meta { display: flex; gap: 3px; flex-wrap: wrap; margin-bottom: 4px; }
.char-delta { font-size: 11px; font-weight: 600; margin-top: 4px; }
.delta-pos  { color: #60a5fa; }
.delta-neg  { color: #f87171; }
.delta-zero { color: #64748b; }
.recon-note { font-size: 10px; color: #64748b; margin-top: 4px; word-break: break-all; }

/* ── badge ── */
.badge { display: inline-block; padding: 1px 5px; border-radius: 3px;
         font-size: 10px; font-weight: 500; cursor: default; }

/* ── column headers ── */
.col-headers th { padding: 7px 10px; background: #0f172a; color: #475569;
                  font-size: 11px; text-align: left; font-weight: 700;
                  border-bottom: 2px solid #1e293b; position: sticky; top: 0; z-index: 10; }
</style>
</head>
<body>

<!-- Coverage header -->
${covHeader}

<!-- Page info + summary -->
<div class="view-header">
  <div class="view-title">Reconcile Fusion View</div>
  <div class="view-meta">
    queryId: <b>${esc(queryId)}</b>
    &nbsp;·&nbsp; session: <b>${esc(sessionId.slice(0, 12))}…</b>
    &nbsp;·&nbsp; ${esc(timestamp)}
  </div>
  <div class="summary-row">
    <span class="stat"><b>${report.snapshot.segments.length}</b> proxy segs</span>
    <span class="stat"><b>${report.expected?.segments.length ?? 0}</b> expected segs</span>
    <span class="stat"><b>${matched}</b> matched</span>
    <span class="stat"><b>${attrOnly}</b> attr-only</span>
    <span class="stat"><b>${serverSide}</b> server-side</span>
    <span class="stat"><b>${expectedOnlySegs.length}</b> expected-only</span>
  </div>
</div>

<!-- 4-column table -->
<table>
  <colgroup>
    <col class="col-raw">
    <col class="col-attr">
    <col class="col-expected">
    <col class="col-recon">
  </colgroup>
  <thead>
    <tr class="col-headers">
      <th title="Actual text from the proxy-intercepted reqBody — ground truth">Raw (reqBody)</th>
      <th title="Parser segment metadata + rule-based attribution — how this segment was classified and identified">Attribution</th>
      <th title="Text reconstructed from JSONL mutations — what the harness intended to send">Expected (virtual)</th>
      <th title="Alignment result between proxy and expected — kind, basis, comparison grade, and char delta">Reconcile</th>
    </tr>
  </thead>
  <tbody>
    ${sectionBlocks}
    ${expectedOnlyBlock}
  </tbody>
</table>

</body>
</html>`;
}
